version: "3.8"

services:
  ponte:
    container_name: ponte
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_TYPE: postgres
      DATABASE_NAME: ponte
      ENVIRONMENT: development
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "npm run migration:run && npm run start"]
    networks:
      - ponte_network

  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ponte
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - ponte_network

networks:
  ponte_network:
